#!/bin/bash
2>/dev/null
SYSTEM_USER_NAME=$(id -un)
if [[ "${SYSTEM_USER_NAME}" != 'root'  ]]
then
    echo -e "\e[1;36m Please run me as root! / Lütfen beni root olarak çalıştırın!\e[1m \n"
    exit 1
fi
echo -e "\e[1;34m
--------------------------------------------------------------                                             
 / ___| | ___  __ _ _ __ | __ ) _   _ / ___|_ __ __ _ ___| |_
| |   | |/ _ \/ _  |  _ \|  _ \| | | | |   | '__/ _  / __| __|
| |___| |  __/ (_| | | | | |_) | |_| | |___| | | (_| \__ \ |_
 \____|_|\___|\__,_|_| |_|____/ \__, |\____|_|  \__,_|___/\__|
                                |___/  
--------------------------------------------------------------\e[1m \n"

read -p "Enlish[1] / Türkçe [2] $foo? [1/2]:" answer
if [[ $answer = 1  ]] ; then

  echo -e "\e[1;36m [+]Cleaning log and cache files,this process takes about a minute.\e[1m \n"
sleep 1

if [[ -f /var/log/* ]]
then
	echo "" > /var/log/*
	sleep 0.5
fi

if [[ -f /var/apache/logs/* ]]
then	
  	echo "" > /var/apache/logs/*
	sleep 0.5
fi
if [[ -f /var/apache2/logs/* ]]
then	
  	echo "" > /var/apache2/logs/*
	sleep 0.5
fi
if [[ -f /tmp/* ]]
then
	echo "" >/tmp/*
	sleep 0.5
fi
if [[ -f /usr/lib/dradis/ruby/2.7.0/gems/dradis-plugins-3.20.0/spec/internal/log/* ]]
then
	echo "" >/usr/lib/dradis/ruby/2.7.0/gems/dradis-plugins-3.20.0/spec/internal/log/*
	sleep 0.5
fi
if [[ -f /usr/lib/dradis/ruby/2.7.0/gems/bootstrap-4.3.1/test/dummy_rails/log/* ]]
then
	echo "" >/usr/lib/dradis/ruby/2.7.0/gems/bootstrap-4.3.1/test/dummy_rails/log/*
	sleep 0.5
fi
if [[ -f /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-4.1.1/spec/dummy/log/* ]]
then
	echo "" >/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-4.1.1/spec/dummy/log/*
	sleep 0.5
fi

if [[ -f /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-4.1.1/spec/dummy/log/* ]]
then
	echo "" >/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-4.1.1/spec/dummy/log/*
	sleep 0.5
fi
if [[ -f /var/apache/log/* ]]
then
	echo "" >/var/apache/log/*
	sleep 0.5
fi
if [[ -f /var/apache2/log/* ]]
then
	echo "" >/var/apache2/log/*
	sleep 0.5
fi
if [[ -f /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/arel-helpers-2.12.0/spec/internal/log/* ]]
then
	echo "" >/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/arel-helpers-2.12.0/spec/internal/log/*
	sleep 0.5
fi
if [[ -f /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.112.0/lib/aws-sdk-core/log/* ]]
then
	echo "" >/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.112.0/lib/aws-sdk-core/log/*
	sleep 0.5
fi
if [[ -f /usr/share/paros/log/* ]]
then
	echo "" >/usr/share/paros/log/*
	sleep 0.5
fi
if [[ -f /usr/share/paros/log/* ]]
then
	echo "" >/usr/share/paros/log/*
	sleep 0.5
fi
if [[ -f /usr/local/apache/log/* ]]
then
	echo "" >/usr/local/apache/log/*
	sleep 0.5
fi
if [[ -f /usr/local/apache2/log/* ]]
then
	echo "" >/usr/local/apache2/log/*
	sleep 0.5
fi
if [[ -f /usr/local/psa/admin/logs/httpsd_access_log/* ]]
then
	echo "" >/usr/local/psa/admin/logs/httpsd_access_log/*
	sleep 0.5
fi
if [[ -f /usr/local/psa/admin/logs/panel.log/* ]]
then
	echo "" >/usr/local/psa/admin/logs/panel.log/*
	sleep 0.5
fi
if [[ -f /usr/share/legion/log/* ]]
then
	echo "" >/usr/share/legion/log/*
	sleep 0.5
fi
if [[ -f $HOME/.ZAP/jbrofuzz/log/* ]]
then
	echo "" >$HOME/.ZAP/jbrofuzz/log/*
	sleep 0.5
fi
if [[ -f /usr/local/apache/logs/* ]]
then
	echo "" >/usr/local/apache/logs/*
	sleep 0.5
fi
if [[ -f /usr/local/apache2/logs/* ]]
then
	echo "" >/usr/local/apache2/logs/*
	sleep 0.5
fi
if [[ -f /etc/sv/tor/log/* ]]
then
	echo "" >/etc/sv/tor/log/*
	sleep 0.5
fi
if [[ -f /usr/lib/dradis/ruby/2.7.0/gems/combustion-0.6.0/spec/dummy/spec/internal/log/* ]]
then
	echo "" >/usr/lib/dradis/ruby/2.7.0/gems/combustion-0.6.0/spec/dummy/spec/internal/log/*
	sleep 0.5
fi
if [[ -f /etc/sv/ssh/log/* ]]
then
	echo "" >/etc/sv/ssh/log/*
	sleep 0.5
fi
if [[ -f /run/log/* ]]
then
	echo "" >/run/log/*
	sleep 0.5
fi
if [[ -f /root/.history ]]
then
	echo "" >/root/.history
	sleep 0.5
fi
if [[ -f $HOME/.zsh_history ]]
then
	echo "" >$HOME/.zsh_history
	sleep 0.5
fi
if [[ -f /root/*_history ]]
then
	echo "" >/root/*_history
	sleep 0.5
fi
if [[ -f /root/.zsh_history ]]
then
	echo "" >/root/.zsh_history
	sleep 0.5
fi

sync; echo 3 > /proc/sys/vm/drop_caches 
sleep 0.5 

echo -e "\e[1;33m Donee! Everywhere looks tidier now :)\e[1m \n"
sleep 1
exit 1
else 
  echo -e "\e[1;32m [+]Log ve cache dosyaları temizleniyor, bu işlem ortalama 1 dakika sürer.\e[1m \n"
sleep 1

if [[ -f /var/log/* ]]
then
	echo "" > /var/log/*
	sleep 0.5
fi

if [[ -f /var/apache/logs/* ]]
then	
  	echo "" > /var/apache/logs/*
	sleep 0.5
fi
if [[ -f /var/apache2/logs/* ]]
then	
  	echo "" > /var/apache2/logs/*
	sleep 0.5
fi
if [[ -f /tmp/* ]]
then
	echo "" >/tmp/*
	sleep 0.5
fi
if [[ -f /usr/lib/dradis/ruby/2.7.0/gems/dradis-plugins-3.20.0/spec/internal/log/* ]]
then
	echo "" >/usr/lib/dradis/ruby/2.7.0/gems/dradis-plugins-3.20.0/spec/internal/log/*
	sleep 0.5
fi
if [[ -f /usr/lib/dradis/ruby/2.7.0/gems/bootstrap-4.3.1/test/dummy_rails/log/* ]]
then
	echo "" >/usr/lib/dradis/ruby/2.7.0/gems/bootstrap-4.3.1/test/dummy_rails/log/*
	sleep 0.5
fi
if [[ -f /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-4.1.1/spec/dummy/log/* ]]
then
	echo "" >/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-4.1.1/spec/dummy/log/*
	sleep 0.5
fi

if [[ -f /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-4.1.1/spec/dummy/log/* ]]
then
	echo "" >/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-4.1.1/spec/dummy/log/*
	sleep 0.5
fi
if [[ -f /var/apache/log/* ]]
then
	echo "" >/var/apache/log/*
	sleep 0.5
fi
if [[ -f /var/apache2/log/* ]]
then
	echo "" >/var/apache2/log/*
	sleep 0.5
fi
if [[ -f /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/arel-helpers-2.12.0/spec/internal/log/* ]]
then
	echo "" >/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/arel-helpers-2.12.0/spec/internal/log/*
	sleep 0.5
fi
if [[ -f /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.112.0/lib/aws-sdk-core/log/* ]]
then
	echo "" >/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.112.0/lib/aws-sdk-core/log/*
	sleep 0.5
fi
if [[ -f /usr/share/paros/log/* ]]
then
	echo "" >/usr/share/paros/log/*
	sleep 0.5
fi
if [[ -f /usr/share/paros/log/* ]]
then
	echo "" >/usr/share/paros/log/*
	sleep 0.5
fi
if [[ -f /usr/local/apache/log/* ]]
then
	echo "" >/usr/local/apache/log/*
	sleep 0.5
fi
if [[ -f /usr/local/apache2/log/* ]]
then
	echo "" >/usr/local/apache2/log/*
	sleep 0.5
fi
if [[ -f /usr/local/psa/admin/logs/httpsd_access_log/* ]]
then
	echo "" >/usr/local/psa/admin/logs/httpsd_access_log/*
	sleep 0.5
fi
if [[ -f /usr/local/psa/admin/logs/panel.log/* ]]
then
	echo "" >/usr/local/psa/admin/logs/panel.log/*
	sleep 0.5
fi
if [[ -f /usr/share/legion/log/* ]]
then
	echo "" >/usr/share/legion/log/*
	sleep 0.5
fi
if [[ -f $HOME/.ZAP/jbrofuzz/log/* ]]
then
	echo "" >$HOME/.ZAP/jbrofuzz/log/*
	sleep 0.5
fi
if [[ -f /usr/local/apache/logs/* ]]
then
	echo "" >/usr/local/apache/logs/*
	sleep 0.5
fi
if [[ -f /usr/local/apache2/logs/* ]]
then
	echo "" >/usr/local/apache2/logs/*
	sleep 0.5
fi
if [[ -f /etc/sv/tor/log/* ]]
then
	echo "" >/etc/sv/tor/log/*
	sleep 0.5
fi
if [[ -f /usr/lib/dradis/ruby/2.7.0/gems/combustion-0.6.0/spec/dummy/spec/internal/log/* ]]
then
	echo "" >/usr/lib/dradis/ruby/2.7.0/gems/combustion-0.6.0/spec/dummy/spec/internal/log/*
	sleep 0.5
fi
if [[ -f /etc/sv/ssh/log/* ]]
then
	echo "" >/etc/sv/ssh/log/*
	sleep 0.5
fi
if [[ -f /run/log/* ]]
then
	echo "" >/run/log/*
	sleep 0.5
fi
if [[ -f /root/.history ]]
then
	echo "" >/root/.history
	sleep 0.5
fi
if [[ -f $HOME/.zsh_history ]]
then
	echo "" >$HOME/.zsh_history
	sleep 0.5
fi
if [[ -f /root/*_history ]]
then
	echo "" >/root/*_history
	sleep 0.5
fi
if [[ -f /root/.zsh_history ]]
then
	echo "" >/root/.zsh_history
	sleep 0.5
fi

sync; echo 3 > /proc/sys/vm/drop_caches 
sleep 0.5 

echo -e "\e[1;33m Bittii! Ortalık şimdi daha derli toplu görünüyor :)\e[1m \n"
sleep 1
exit 1
fi
